version: "3.7"

services:
    # add a dependency here (e.g. database, ..)
    tests:
        image: jssoft/node_browsertests
        command: "npm run test"
        volumes:
            - ./example:/usr/app
