name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash .ci/runChecks.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: browser-actions/setup-chrome@latest
      - run: npm ci
      - run: npm run build
      - run: npm run test
